# Gitleaks Configuration for Radarr MVP
# This configuration extends the default rules and adds project-specific customizations

[extend]
# Use the default gitleaks configuration as base
useDefault = true

# Global allowlist for common false positives
[allowlist]
description = "Global allowlist for Radarr MVP"

# Allow documentation examples with placeholder passwords
paths = [
    "README.md",
    "docs/.*\\.md",
    ".*\\.example",
    ".*\\.template",
    "config/.*\\.example",
    "config/.*\\.template"
]

# Allow specific patterns that are clearly examples/placeholders
regexes = [
    # Placeholder passwords
    "CHANGE_ME",
    "YOUR_PASSWORD",
    "YOUR_.*_API_KEY",
    "YOUR_.*_SECRET",
    "CHANGE_ME_.*",
    "REPLACE_.*",
    "PLACEHOLDER",
    "example\\.com",
    "localhost",
    # Common test/example values
    "password123",
    "admin",
    "adminadmin",
    "test",
    "demo",
    # PostgreSQL example URLs with placeholders
    "postgresql://[^:]+:CHANGE_ME",
    "postgresql://[^:]+:\\[PASSWORD\\]",
    "postgresql://[^:]+:\\[YOUR_PASSWORD\\]",
    # Environment variable references (not actual values)
    "\\$\\{.*\\}",
    "\\$[A-Z_]+",
]

# Project-specific rule configurations
[[rules]]
id = "database-connection-string"
[rules.allowlist]
# Allow database URLs in documentation and scripts with placeholders
regexes = [
    "postgresql://[^:]+:CHANGE_ME",
    "postgresql://[^:]+:\\[PASSWORD\\]",
    "postgresql://[^:]+:\\[YOUR_PASSWORD\\]",
    "postgresql://localhost/radarr"  # No password
]
paths = [
    "scripts/.*\\.sh",
    "README.md",
    "docs/.*"
]

[[rules]]
id = "postgresql-password"
[rules.allowlist]
# Allow PostgreSQL passwords that are clearly placeholders
regexes = [
    "CHANGE_ME",
    "YOUR_PASSWORD",
    "\\[PASSWORD\\]",
    "\\[YOUR_PASSWORD\\]"
]

[[rules]]
id = "generic-api-key"
[rules.allowlist]
# Allow API keys that are clearly placeholders
regexes = [
    "YOUR_.*_API_KEY",
    "YOUR_.*_KEY",
    "CHANGE_ME.*"
]
paths = [
    "config/.*\\.template",
    "config/.*\\.example",
    ".*\\.env\\.example",
    ".*\\.env\\.template"
]

# Additional custom rules
[[rules]]
id = "radarr-custom-hardcoded-password"
description = "Radarr Custom - Hardcoded password detection"
regex = '''(?i)(password|passwd|pwd|pass)\s*=\s*["'][^"']{8,}["']'''
tags = ["password", "security"]
[rules.allowlist]
paths = [
    ".*\\.example",
    ".*\\.template",
    "docs/.*"
]
regexes = [
    "CHANGE_ME",
    "YOUR_PASSWORD",
    "PLACEHOLDER"
]

[[rules]]
id = "radarr-custom-api-key"
description = "Radarr Custom - API Key detection"
regex = '''(?i)(api[_-]?key|apikey|api[_-]?secret)\s*=\s*["'][a-zA-Z0-9]{20,}["']'''
tags = ["api-key", "security"]
[rules.allowlist]
paths = [
    ".*\\.example",
    ".*\\.template"
]
regexes = [
    "YOUR_",
    "CHANGE_ME",
    "PLACEHOLDER"
]

# File patterns to completely skip
[extend.files]
# Skip files that should never contain real secrets
paths = [
    ".*\\.example$",
    ".*\\.template$",
    ".*\\.sample$",
    "target/.*",
    "node_modules/.*",
    "dist/.*",
    "build/.*",
    ".git/.*"
]