# .pre-commit-config.yaml
repos:
  - repo: local
    hooks:
      - id: fmt
        name: Rust fmt
        entry: cargo fmt --
        language: system
        types: [rust]
        
      - id: clippy
        name: Rust clippy
        entry: cargo clippy -- -D warnings
        language: system
        types: [rust]
        pass_filenames: false
        
      - id: test
        name: Rust test
        entry: cargo test
        language: system
        types: [rust]
        pass_filenames: false
        
      - id: audit
        name: Cargo audit
        entry: cargo audit
        language: system
        pass_filenames: false
        
      - id: secrets
        name: Detect secrets
        entry: gitleaks detect --source . --verbose
        language: system
        pass_filenames: false