apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unified-radarr

resources:
- ../../base
- storageclass.yaml
- exporters.yaml
- backup.yaml
- cert-manager.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- configmap-patch.yaml
- secret-patch.yaml

images:
- name: unified-radarr
  newTag: "1.0.0"

replicas:
- name: unified-radarr
  count: 5

commonLabels:
  environment: production
  version: "1.0.0"

commonAnnotations:
  deployment.timestamp: "2025-01-01T00:00:00Z"
  managed-by: "kustomize"
  
configMapGenerator:
- name: prometheus-config
  files:
  - prometheus.yml
- name: prometheus-rules
  files:
  - alerts.yml
- name: grafana-provisioning
  files:
  - datasources.yml
  - dashboards.yml
- name: grafana-dashboards
  files:
  - radarr-overview.json
  - system-metrics.json
  - automation-pipeline.json