apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: radarr-mvp

resources:
- ../../base
- storageclass.yaml
- exporters.yaml
- backup.yaml
- cert-manager.yaml
- gateway-api.yaml
- external-secrets-prod.yaml
- prometheus-rules.yaml
- grafana-dashboards.yaml
- istio-config.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- configmap-patch.yaml
- secret-patch.yaml

images:
- name: radarr-mvp
  newTag: "1.0.0"
  newName: your-registry.com/radarr-mvp

replicas:
- name: radarr-mvp
  count: 5

commonLabels:
  environment: production
  version: "1.0.0"
  tier: production
  security-scan: "enabled"

commonAnnotations:
  deployment.timestamp: "2025-01-21T00:00:00Z"
  managed-by: "kustomize"
  contact: "team@radarr.com"
  documentation: "https://docs.radarr.com/deployment"
  monitoring: "prometheus"
  security.policy: "restricted"
  
configMapGenerator:
- name: prometheus-config
  files:
  - prometheus.yml
- name: prometheus-rules
  files:
  - alerts.yml
- name: grafana-provisioning
  files:
  - datasources.yml
  - dashboards.yml
- name: grafana-dashboards
  files:
  - radarr-overview.json
  - system-metrics.json
  - automation-pipeline.json
- name: otel-config
  files:
  - otel-collector.yaml
- name: istio-config
  files:
  - virtualservice.yaml
  - destinationrule.yaml
  - authorizationpolicy.yaml