# Production Prometheus Configuration for Radarr MVP
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'unified-radarr-prod'
    environment: 'production'
    region: 'us-central1'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093
      path_prefix: /alertmanager
      scheme: http

scrape_configs:
  # Kubernetes API Server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https

  # Kubernetes Nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)
    - target_label: __address__
      replacement: kubernetes.default.svc:443
    - source_labels: [__meta_kubernetes_node_name]
      regex: (.+)
      target_label: __metrics_path__
      replacement: /api/v1/nodes/${1}/proxy/metrics

  # Kubernetes Pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__
    - action: labelmap
      regex: __meta_kubernetes_pod_label_(.+)
    - source_labels: [__meta_kubernetes_namespace]
      action: replace
      target_label: kubernetes_namespace
    - source_labels: [__meta_kubernetes_pod_name]
      action: replace
      target_label: kubernetes_pod_name

  # Radarr MVP Application
  - job_name: 'unified-radarr'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - unified-radarr
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: unified-radarr-service
    - source_labels: [__meta_kubernetes_endpoint_port_name]
      action: keep
      regex: metrics
    metrics_path: /metrics
    scrape_interval: 15s
    scrape_timeout: 10s

  # PostgreSQL Exporter
  - job_name: 'postgres-exporter'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - unified-radarr
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: postgres-exporter-service
    scrape_interval: 30s

  # Redis Exporter
  - job_name: 'redis-exporter'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - unified-radarr
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: redis-exporter-service
    scrape_interval: 30s

  # Node Exporter
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - unified-radarr
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: node-exporter-service
    scrape_interval: 15s

  # Prometheus Self-Monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s

  # Grafana
  - job_name: 'grafana'
    kubernetes_sd_configs:
    - role: endpoints
      namespaces:
        names:
        - unified-radarr
    relabel_configs:
    - source_labels: [__meta_kubernetes_service_name]
      action: keep
      regex: grafana-service
    metrics_path: /metrics
    scrape_interval: 30s

# Remote write configuration for long-term storage (optional)
# remote_write:
#   - url: "https://prometheus-remote-write.example.com/api/v1/write"
#     basic_auth:
#       username: "username"
#       password: "password"