apiVersion: v1
kind: ConfigMap
metadata:
  name: unified-radarr-config
  namespace: unified-radarr
data:
  RUST_LOG: "info"
  DATABASE_URL: "postgres://radarr:$(POSTGRES_PASSWORD)@postgres-service:5432/radarr"
  REDIS_URL: "redis://:$(REDIS_PASSWORD)@redis-service:6379"
  METRICS_PORT: "9090"
  HEALTH_CHECK_INTERVAL: "30"
  MAX_CONCURRENT_DOWNLOADS: "5"
  DOWNLOAD_TIMEOUT: "300"
  CLEANUP_INTERVAL: "3600"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: unified-radarr
data:
  POSTGRES_DB: "radarr"
  POSTGRES_USER: "radarr"
  POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
  PGDATA: "/var/lib/postgresql/data/pgdata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: unified-radarr
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    save 900 1
    save 300 10
    save 60 10000
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    timeout 300
    tcp-keepalive 300