apiVersion: v1
kind: ConfigMap
metadata:
  name: radarr-mvp-config
  namespace: radarr-mvp
data:
  # Server Configuration
  RADARR_HOST: "0.0.0.0"
  RADARR_PORT: "7878"
  RADARR_MAX_CONNECTIONS: "1000"
  RADARR_REQUEST_TIMEOUT: "30"
  
  # Database Configuration
  DATABASE_MAX_CONNECTIONS: "20"
  DATABASE_CONNECT_TIMEOUT: "30"
  DATABASE_LOG_QUERIES: "false"
  
  # External Services
  PROWLARR_BASE_URL: "http://prowlarr:9696"
  PROWLARR_TIMEOUT: "30"
  PROWLARR_RATE_LIMIT: "60"
  QBITTORRENT_BASE_URL: "http://qbittorrent:8080"
  QBITTORRENT_USERNAME: "admin"
  QBITTORRENT_TIMEOUT: "30"
  
  # Logging
  RUST_LOG: "info"
  LOG_JSON_FORMAT: "true"
  LOG_FILE: "/var/log/radarr/radarr.log"
  
  # Application
  WEB_ROOT: "/usr/local/share/radarr/web"
  DATA_DIR: "/var/lib/radarr"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: radarr-mvp
data:
  POSTGRES_DB: "radarr"
  POSTGRES_USER: "radarr"
  POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
  PGDATA: "/var/lib/postgresql/data/pgdata"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: redis-config
  namespace: radarr-mvp
data:
  redis.conf: |
    appendonly yes
    appendfsync everysec
    auto-aof-rewrite-percentage 100
    auto-aof-rewrite-min-size 64mb
    save 900 1
    save 300 10
    save 60 10000
    maxmemory 256mb
    maxmemory-policy allkeys-lru
    timeout 300
    tcp-keepalive 300