apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - deployment.yaml
  - service.yaml
  - postgres.yaml
  - redis.yaml
  - monitoring.yaml
  - ingress.yaml
  - networkpolicy.yaml
  - pdb.yaml
  - hpa.yaml
  - vpa.yaml
  - keda.yaml
  - servicemonitor.yaml
  - podsecuritypolicy.yaml

commonLabels:
  app.kubernetes.io/name: radarr-mvp
  app.kubernetes.io/part-of: radarr-automation
  app.kubernetes.io/version: "1.0.0"
  app.kubernetes.io/managed-by: kustomize

commonAnnotations:
  version: "1.0.0"
  managed-by: "kustomize"
  prometheus.io/scrape: "true"
  instrumentation.opentelemetry.io/inject-auto: "true"