apiVersion: v1
kind: Namespace
metadata:
  name: unified-radarr
  labels:
    name: unified-radarr
    environment: production
    app.kubernetes.io/name: unified-radarr
    app.kubernetes.io/component: namespace
  annotations:
    description: "Radarr MVP automation system namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: unified-radarr-quota
  namespace: unified-radarr
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: unified-radarr-limits
  namespace: unified-radarr
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container