apiVersion: v1
kind: Namespace
metadata:
  name: radarr-mvp
  labels:
    name: radarr-mvp
    environment: production
    app.kubernetes.io/name: radarr-mvp
    app.kubernetes.io/component: namespace
  annotations:
    description: "Radarr MVP automation system namespace"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: radarr-mvp-quota
  namespace: radarr-mvp
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
    secrets: "20"
    configmaps: "20"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: radarr-mvp-limits
  namespace: radarr-mvp
spec:
  limits:
  - default:
      cpu: 500m
      memory: 512Mi
    defaultRequest:
      cpu: 100m
      memory: 128Mi
    type: Container