apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: unified-radarr-pdb
  namespace: unified-radarr
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/component: application
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: postgres-pdb
  namespace: unified-radarr
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: database
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: redis-pdb
  namespace: unified-radarr
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: cache