apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: radarr-mvp
  name: radarr-mvp-role
  labels:
    app.kubernetes.io/name: radarr-mvp
    app.kubernetes.io/component: security
rules:
- apiGroups: [""]
  resources: ["secrets", "configmaps"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: [""]
  resources: ["persistentvolumeclaims"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: radarr-mvp-rolebinding
  namespace: radarr-mvp
  labels:
    app.kubernetes.io/name: radarr-mvp
    app.kubernetes.io/component: security
subjects:
- kind: ServiceAccount
  name: radarr-mvp
  namespace: radarr-mvp
roleRef:
  kind: Role
  name: radarr-mvp-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: radarr-mvp-pdb
  namespace: radarr-mvp
  labels:
    app.kubernetes.io/name: radarr-mvp
    app.kubernetes.io/component: availability
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr-mvp
      app.kubernetes.io/component: application
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: radarr-mvp-postgres-pdb
  namespace: radarr-mvp
  labels:
    app.kubernetes.io/name: radarr-mvp
    app.kubernetes.io/component: database
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: radarr-mvp
      app.kubernetes.io/component: database
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: radarr-mvp-monitoring
  namespace: radarr-mvp
  labels:
    app.kubernetes.io/name: radarr-mvp
    app.kubernetes.io/component: monitoring
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT:role/radarr-mvp-monitoring-role
automountServiceAccountToken: true
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: radarr-mvp-monitoring
  labels:
    app.kubernetes.io/name: radarr-mvp
    app.kubernetes.io/component: monitoring
rules:
- apiGroups: [""]
  resources: ["nodes", "nodes/proxy", "services", "endpoints", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["extensions"]
  resources: ["ingresses"]
  verbs: ["get", "list", "watch"]
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: radarr-mvp-monitoring
  labels:
    app.kubernetes.io/name: radarr-mvp
    app.kubernetes.io/component: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: radarr-mvp-monitoring
subjects:
- kind: ServiceAccount
  name: radarr-mvp-monitoring
  namespace: radarr-mvp