apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: unified-radarr

resources:
- ../../base
- secret-manager-csi.yaml
- external-secrets.yaml

patchesStrategicMerge:
- deployment-patch.yaml
- service-patch.yaml
- configmap-patch.yaml
- ingress-patch.yaml

images:
- name: unified-radarr
  newTag: "dev-latest"

replicas:
- name: unified-radarr
  count: 1

commonLabels:
  environment: dev
  version: "dev"
  tier: "development"

commonAnnotations:
  deployment.timestamp: "2025-01-01T00:00:00Z"
  managed-by: "kustomize"
  
configMapGenerator:
- name: radarr-config
  literals:
  - DATABASE_URL=postgresql://radarr:$(POSTGRES_PASSWORD)@postgres:5432/radarr_dev
  - REDIS_URL=redis://:$(REDIS_PASSWORD)@redis:6379/0
  - LOG_LEVEL=debug
  - ENVIRONMENT=dev
  - API_RATE_LIMIT=1000
  - ENABLE_METRICS=true
  - BACKUP_ENABLED=false
  
secretGenerator:
- name: radarr-dev-secrets
  literals:
  - TMDB_API_KEY=dev-tmdb-key-placeholder
  - HDBITS_API_KEY=dev-hdbits-key-placeholder
  options:
    disableNameSuffixHash: true